# Generated by Django 3.1.1 on 2021-08-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('unitsize', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sievesize', models.CharField(max_length=120)),
            ],
        ),
    ]
