# Generated by Django 3.1.1 on 2021-08-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20210731_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='finerpercent',
            field=models.CharField(default='1, 0.92, 0.82, 0.58, 0.14', max_length=120),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='height',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='sievesize',
            field=models.CharField(default='4.75, 2.36, 1.18, 0.6, 0.3', max_length=120),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='unitsize',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='width',
            field=models.IntegerField(default=800),
        ),
    ]
